default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: timesnakajima_development

test:
  <<: *default
  database: timesnakajima_test

production:
  <<: *default
  database: timesnakajima_production
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
